
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


def relative_to_assets(path: str) -> Path:
    # Return the full path by joining ASSETS_PATH with the provided relative path
    return ASSETS_PATH / Path(path)


BASE_PATH = Path(__file__).resolve().parent.parent

# Define the relative path to the assets directory
ASSETS_REL_PATH = Path("assets/frame0a")

# Define the absolute path to the assets directory
ASSETS_PATH = BASE_PATH / ASSETS_REL_PATH


window = Tk()

window.geometry("700x550")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 550,
    width = 700,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    700.0,
    62.0,
    fill="#00116B",
    outline="")

canvas.create_text(
    13.0,
    14.0,
    anchor="nw",
    text="Menu to Excel Converter",
    fill="#FFFFFF",
    font=("Inter Bold", 28 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    491.0,
    306.0,
    image=image_image_1
)

canvas.create_rectangle(
    0.0,
    62.0,
    281.0,
    550.0,
    fill="#292929",
    outline="")

canvas.create_rectangle(
    14.0,
    76.0,
    266.0,
    282.0,
    fill="#373737",
    outline="")

canvas.create_rectangle(
    13.0,
    296.0,
    265.0,
    462.0,
    fill="#000000",
    outline="")

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    140.0,
    150.0,
    image=image_image_2
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=75.0,
    y=222.0,
    width=131.0,
    height=32.0
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    490.0,
    221.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    490.0,
    458.0,
    image=image_image_4
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=98.0,
    y=476.0,
    width=168.0,
    height=49.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=98.0,
    y=476.0,
    width=168.0,
    height=49.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=13.0,
    y=476.0,
    width=75.0,
    height=49.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=407.0,
    y=83.0,
    width=20.0,
    height=20.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=555.0,
    y=83.0,
    width=20.0,
    height=20.0
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    491.0,
    93.0,
    image=image_image_5
)

canvas.create_text(
    429.0,
    84.0,
    anchor="nw",
    text="Sheet 1",
    fill="#FFFFFF",
    font=("Inter Bold", 14 * -1)
)

canvas.create_text(
    491.0,
    389.0,
    anchor="nw",
    text="Export Excel ",
    fill="#1E2BA3",
    font=("Inter Bold", 16 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    393.0,
    458.5,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#8D8D8D",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=320.0,
    y=389.0,
    width=146.0,
    height=137.0
)

canvas.create_text(
    490.0,
    424.0,
    anchor="nw",
    text="File Name",
    fill="#1E2BA3",
    font=("Inter Bold", 12 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    579.0,
    457.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=500.0,
    y=445.0,
    width=158.0,
    height=23.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=490.0,
    y=479.0,
    width=52.0,
    height=45.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_8 clicked"),
    relief="flat"
)
button_8.place(
    x=550.0,
    y=480.0,
    width=118.0,
    height=45.0
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    203.0,
    85.0,
    image=image_image_6
)

# image_image_7 = PhotoImage(
#     file=relative_to_assets("image_7.png"))
# image_7 = canvas.create_image(
#     203.0,
#     272.0,
#     image=image_image_7
# )

# image_image_8 = PhotoImage(
#     file=relative_to_assets("image_8.png"))
# image_8 = canvas.create_image(
#     77.0,
#     272.0,
#     image=image_image_8
# )

canvas.create_text(
    21.0,
    79.0,
    anchor="nw",
    text="Images",
    fill="#8F8F8F",
    font=("Inter Bold", 15 * -1)
)
window.resizable(False, False)
window.mainloop()